// Generated by CoffeeScript 1.3.3

/*
if window.NameSpaces == undefined
    window.NameSpaces = {}
*/


(function() {
  var MyClass;

  MyClass = (function() {
    /*
        @member = "@member"
        @MEMBER = "@MEMBER"
    */

    function MyClass(option) {
      this.option = {};
      this._extends(option);
      this._init();
    }

    /*
        member = "private"
        getMember:->
            member
    */


    MyClass.prototype._extends = function(option) {
      var param;
      if (option === void 0) {
        return;
      }
      for (param in option) {
        this.option[param] = option[param];
      }
      return this;
    };

    MyClass.prototype._init = function() {
      return this;
    };

    return MyClass;

  })();

}).call(this);
